import os,sys,fnmatch
the_path=raw_input("enter the path : ")
#assert os.path.exists(the_path),"Specified path does not exist"
count=len(fnmatch.filter(os.listdir(the_path),'*'))
if(count==0):
 new_file=os.path.join(the_path,'newfile.txt')
 f=open(new_file,"w")
 f.write("Auto generated file")
 f.close()
 from git import Repo,remote
 repo=Repo(new_file)
 repo=git.Repo("anushagitrepo")
 repo.git.add(new_file)
 repo.git.commit("Auto commit1")
 repo.git.push('origin',master)
else:
 user_response=raw_input("Do you want new file to be created in the path specified ? y/n     ")
 if(user_response=="y" or user_response=="Y" or user_response=="yes"):
  new_file=os.path.join(the_path,'newfile.txt')
  f=open(new_file,"w")
  f.write("Autogenerated file")
  f.close()
  repo=git.Repo("anushagitrepo")
  repo.git.add(new_file)
  repo.git.commit("Auto Commit")
  repo.git.push('origin',master) 
